# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "1220904d2fdcd970dd0d216211d092eb3ef6da01117163cc9393ab845a1d66c029d9";
    path = fetchzip {
      url = "https://github.com/ikskuh/zig-args/archive/03af1b6c5bfda9646a562c861055024daed5b238.tar.gz";
      hash = "sha256-B2jjhlCpZ0Ii4T9vhFK2T+vrb2QNMBPUvZq/i92Jef8=";
    };
  }
]
